version: '3.3'

services:
  octoprint:
    image: octoprint/octoprint
    restart: unless-stopped
    ports:
      - 81:80
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    volumes:
      - octoprint:/octoprint
    environment:
      - ENABLE_MJPG_STREAMER=true

  config-editor:
    image: linuxserver/code-server
    ports:
      - 8443:8443
    depends_on:
      - octoprint
    restart: unless-stopped
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Zurich
    volumes:
      - octoprint:/octoprint

  ngrok-octo:
    image: ngrok/ngrok:latest
    restart: always
    depends_on:
      - octoprint
    command:
      - "http"
      - "http://octoprint:80"
      - "--oauth=google"
      - "--oauth-allow-email=janhasler01@gmail.com"
      - "--url=${NGROK_URL}"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    ports:
      - 4040:4040

  ngrok-jpeg:
    image: ngrok/ngrok:latest
    network_mode: host
    restart: always
    command:
      - "http"
      - "http://localhost:8080"
      - "--oauth=google"
      - "--oauth-allow-email=janhasler01@gmail.com"
      - "--url=${NGROK_URL_2}"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN_2}
    ports:
      - 4041:4041
volumes:
  octoprint: {}
